const menuData = {
  vodka: [
    {
      drinkId: "vodka-coca",
      itemName: "Vodka y Coca",
      unitPrice: 100,
      volume: "473ml",
      imageUrl: "/img/vodka-coca-240x240.webp",
      available: true,
      categoryId: "coctel",
    },
    {
      drinkId: "azulito",
      itemName: "Azulito",
      unitPrice: 100,
      volume: "473ml",
      imageUrl: "/img/azulito-240x240.webp",
      available: true,
      categoryId: "coctel",
    },
    {
      drinkId: "vodka-jugo",
      itemName: "Vodka y Jugo",
      unitPrice: 100,
      volume: "473ml",
      imageUrl: "/img/vodka-jugo-240x240.webp",
      available: true,
      categoryId: "coctel",
    },
  ],
  ron: [
    {
      drinkId: "ron-coca",
      itemName: "Ron y Coca",
      unitPrice: 100,
      volume: "473ml",
      imageUrl: "/img/ron-coca-240x240.webp",
      available: true,
      categoryId: "coctel",
    },
    {
      drinkId: "mojito",
      itemName: "Mojito",
      unitPrice: 100,
      volume: "473ml",
      imageUrl: "/img/mojito-240x240.webp",
      available: true,
      categoryId: "coctel",
    },
    {
      drinkId: "mojito-mango",
      itemName: "Mojito Mango",
      unitPrice: 100,
      volume: "473ml",
      imageUrl: "/img/mojito-mango-240x240.webp",
      available: true,
      categoryId: "coctel",
    },
    {
      drinkId: "pina-colada",
      itemName: "Piña Colada",
      unitPrice: 100,
      volume: "473ml",
      imageUrl: "/img/pina-colada-240x240.webp",
      available: true,
      categoryId: "coctel",
    },
  ],
  tequila: [
    {
      drinkId: "teq-coca",
      itemName: "Tequila y Coca",
      unitPrice: 100,
      volume: "473ml",
      imageUrl: "/img/tequila-coca-240x240.webp",
      available: true,
      categoryId: "coctel",
    },
    {
      drinkId: "teq-squirt",
      itemName: "Tequila Squirt",
      unitPrice: 100,
      volume: "473ml",
      imageUrl: "/img/tequila-squirt-240x240.webp",
      available: true,
      categoryId: "coctel",
    },
    {
      drinkId: "cantarito",
      itemName: "Cantarito",
      unitPrice: 100,
      volume: "473ml",
      imageUrl: "/img/cantarito-240x240.webp",
      available: true,
      categoryId: "coctel",
    },
  ],
  whiskey: [
    {
      drinkId: "whis-coca",
      itemName: "Whiskey y Coca-Cola",
      unitPrice: 100,
      volume: "473ml",
      imageUrl: "/img/whiskey-coca-240x240.webp",
      available: true,
      categoryId: "coctel",
    },
    {
      drinkId: "whis-manz",
      itemName: "Whiskey y Manzana",
      unitPrice: 100,
      volume: "473ml",
      imageUrl: "/img/whiskey-manzana-240x240.webp",
      available: true,
      categoryId: "coctel",
    },
    {
      drinkId: "whis-agua",
      itemName: "Whiskey y Agua Mineral",
      unitPrice: 100,
      volume: "473ml",
      imageUrl: "/img/whiskey-agua-240x240.webp",
      available: true,
      categoryId: "coctel",
    },
  ],
  cervezas: [
    {
      drinkId: "heineken",
      itemName: "Heineken",
      unitPrice: 50,
      volume: "473ml",
      imageUrl: "/img/heineken-240x240.webp",
      available: true,
      categoryId: "cerveza",
    },
    {
      drinkId: "corona",
      itemName: "Corona",
      unitPrice: 50,
      volume: "473ml",
      imageUrl: "/img/corona-240x240.webp",
      available: true,
      categoryId: "cerveza",
    },
    {
      drinkId: "victoria",
      itemName: "Victoria",
      unitPrice: 50,
      volume: "473ml",
      imageUrl: "/img/victoria-240x240.webp",
      available: true,
      categoryId: "cerveza",
    },
  ],
  refrescos: [
    {
      drinkId: "coca",
      itemName: "Coca Cola",
      unitPrice: 30,
      volume: "473ml",
      imageUrl: "/img/coca-cola-240x240.webp",
      available: true,
      categoryId: "refresco",
    },
    {
      drinkId: "sprite",
      itemName: "Sprite",
      unitPrice: 30,
      volume: "473ml",
      imageUrl: "/img/sprite-240x240.webp",
      available: true,
      categoryId: "refresco",
    },
    {
      drinkId: "squirt",
      itemName: "Squirt",
      unitPrice: 30,
      volume: "473ml",
      imageUrl: "/img/squirt-240x240.webp",
      available: true,
      categoryId: "refresco",
    },
    {
      drinkId: "manzanita",
      itemName: "Manzanita",
      unitPrice: 30,
      volume: "473ml",
      imageUrl: "/img/manzanita-240x240.jpg",
      available: true,
      categoryId: "refresco",
    },
  ],
  mocteles: [
    {
      drinkId: "min-limon",
      itemName: "Agua Mineral, Limón y Sal",
      unitPrice: 50,
      volume: "473ml",
      imageUrl: "/img/agua-mineral-limon-sal-240x240.jpg",
      available: true,
      categoryId: "moctel",
    },
    {
      drinkId: "min-jugo",
      itemName: "Agua Mineral y Jugo",
      unitPrice: 50,
      volume: "473ml",
      imageUrl: "/img/agua-mineral-jugo-240x240.png",
      available: true,
      categoryId: "moctel",
    },
    {
      drinkId: "moj-sin",
      itemName: "Mojito Sin Alcohol",
      unitPrice: 50,
      volume: "473ml",
      imageUrl: "/img/mojito-240x240.webp",
      available: true,
      categoryId: "moctel",
    },
    {
      drinkId: "azu-sin",
      itemName: "Azulito Sin Alcohol",
      unitPrice: 50,
      volume: "473ml",
      imageUrl: "/img/azulito-240x240.webp",
      available: true,
      categoryId: "moctel",
    },
  ],
  jugos: [
    {
      drinkId: "j-naranja",
      itemName: "Jugo Naranja",
      unitPrice: 30,
      volume: "473ml",
      imageUrl: "/img/jumex-naranja-240x240.jpg",
      available: true,
      categoryId: "jugo",
    },
    {
      drinkId: "j-manzana",
      itemName: "Jugo Manzana",
      unitPrice: 30,
      volume: "473ml",
      imageUrl: "/img/jumex-manzana-240x240.jpg",
      available: true,
      categoryId: "jugo",
    },
    {
      drinkId: "j-uva",
      itemName: "Jugo Uva",
      unitPrice: 30,
      volume: "473ml",
      imageUrl: "/img/jumex-uva-240x240.jpg",
      available: true,
      categoryId: "jugo",
    },
    {
      drinkId: "j-mango",
      itemName: "Jugo Mango",
      unitPrice: 30,
      volume: "473ml",
      imageUrl: "/img/jumex-mango-240x240.jpg",
      available: true,
      categoryId: "jugo",
    },
    {
      drinkId: "j-pina",
      itemName: "Jugo Piña",
      unitPrice: 30,
      volume: "473ml",
      imageUrl: "/img/jumex-pina-240x240.jpg",
      available: true,
      categoryId: "jugo",
    },
    {
      drinkId: "j-durazno",
      itemName: "Jugo Durazno",
      unitPrice: 30,
      volume: "473ml",
      imageUrl: "/img/jumex-durazno-240x240.jpg",
      available: true,
      categoryId: "jugo",
    },
    {
      drinkId: "j-pina-coco",
      itemName: "Jugo Piña Coco",
      unitPrice: 30,
      volume: "473ml",
      imageUrl: "/img/jumex-pina-coco-240x240.jpg",
      available: true,
      categoryId: "jugo",
    },
  ],
  aguas: [
    {
      drinkId: "agua",
      itemName: "Agua",
      unitPrice: 20,
      volume: "473ml",
      imageUrl: "/img/ciel-240x240.jpg",
      available: true,
      categoryId: "agua",
    },
    {
      drinkId: "mineral",
      itemName: "Agua Mineral",
      unitPrice: 30,
      volume: "473ml",
      imageUrl: "/img/penafiel-240x240.webp",
      available: true,
      categoryId: "agua",
    },
  ],
  botanas: [
    {
      drinkId: "chicharron",
      itemName: "Chicharrones",
      unitPrice: 20,
      volume: "473ml",
      imageUrl: "/img/chicharron-240x240.png",
      available: true,
      categoryId: "botana",
    },
  ],
};

export default menuData;
