const menuData = {
  vodka: [
    {
      itemName: "Vodka y Coca",
      price: 100,
      amount: "473ml",
      imageUrl: "/img/vodka-coca-240x240.webp",
      available: true,
    },
    {
      itemName: "Azulito",
      price: 100,
      amount: "473ml",
      imageUrl: "/img/azulito-240x240.webp",
      available: true,
    },
    {
      itemName: "Vodka y Jugo",
      price: 100,
      amount: "473ml",
      imageUrl: "/img/vodka-jugo-240x240.webp",
      available: true,
    },
  ],
  ron: [
    {
      itemName: "Ron y Coca",
      price: 100,
      amount: "473ml",
      imageUrl: "/img/ron-coca-240x240.webp",
      available: true,
    },
    {
      itemName: "Mojito",
      price: 100,
      amount: "473ml",
      imageUrl: "/img/mojito-240x240.webp",
      available: true,
    },
    {
      itemName: "Mojito Mango",
      price: 100,
      amount: "473ml",
      imageUrl: "/img/mojito-mango-240x240.webp",
      available: true,
    },
    {
      itemName: "Piña Colada",
      price: 100,
      amount: "473ml",
      imageUrl: "/img/pina-colada-240x240.webp",
      available: true,
    },
  ],
  tequila: [
    {
      itemName: "Tequila y Coca",
      price: 100,
      amount: "473ml",
      imageUrl: "/img/tequila-coca-240x240.webp",
      available: true,
    },
    {
      itemName: "Tequila Squirt",
      price: 100,
      amount: "473ml",
      imageUrl: "/img/tequila-squirt-240x240.webp",
      available: true,
    },
    {
      itemName: "Cantarito",
      price: 100,
      amount: "473ml",
      imageUrl: "/img/cantarito-240x240.webp",
      available: true,
    },
  ],
  whiskey: [
    {
      itemName: "Whiskey y Coca-Cola",
      price: 100,
      amount: "473ml",
      imageUrl: "/img/whiskey-coca-240x240.webp",
      available: true,
    },
    {
      itemName: "Whiskey y Manzana",
      price: 100,
      amount: "473ml",
      imageUrl: "/img/whiskey-manzana-240x240.webp",
      available: true,
    },
    {
      itemName: "Whiskey y Agua Mineral",
      price: 100,
      amount: "473ml",
      imageUrl: "/img/whiskey-agua-240x240.webp",
      available: true,
    },
  ],
  cervezas: [
    {
      itemName: "Heineken",
      price: 50,
      amount: "473ml",
      imageUrl: "/img/heineken-240x240.webp",
      available: true,
    },
    {
      itemName: "Corona",
      price: 50,
      amount: "473ml",
      imageUrl: "/img/corona-240x240.webp",
      available: true,
    },
    {
      itemName: "Victoria",
      price: 50,
      amount: "473ml",
      imageUrl: "/img/victoria-240x240.webp",
      available: true,
    },
  ],
  refrescos: [
    {
      itemName: "Coca Cola",
      price: 30,
      amount: "473ml",
      imageUrl: "/img/coca-cola-240x240.webp",
      available: true,
    },
    {
      itemName: "Sprite",
      price: 30,
      amount: "473ml",
      imageUrl: "/img/sprite-240x240.webp",
      available: true,
    },
    {
      itemName: "Squirt",
      price: 30,
      amount: "473ml",
      imageUrl: "/img/squirt-240x240.webp",
      available: true,
    },
    {
      itemName: "Manzanita",
      price: 30,
      amount: "473ml",
      imageUrl: "/img/manzanita-240x240.jpg",
      available: true,
    },
  ],
  mocteles: [
    {
      itemName: "Agua Mineral, Limón y Sal",
      price: 50,
      amount: "473ml",
      imageUrl: "/img/agua-mineral-limon-sal-240x240.jpg",
      available: true,
    },
    {
      itemName: "Agua Mineral y Jugo",
      price: 50,
      amount: "473ml",
      imageUrl: "/img/agua-mineral-jugo-240x240.png",
      available: true,
    },
    {
      itemName: "Mojito Sin Alcohol",
      price: 50,
      amount: "473ml",
      imageUrl: "/img/mojito-240x240.webp",
      available: true,
    },
    {
      itemName: "Azulito Sin Alcohol",
      price: 50,
      amount: "473ml",
      imageUrl: "/img/azulito-240x240.webp",
      available: true,
    },
  ],
  jugos: [
    {
      itemName: "Jugo Naranja",
      price: 30,
      amount: "473ml",
      imageUrl: "/img/jumex-naranja-240x240.jpg",
      available: true,
    },
    {
      itemName: "Jugo Manzana",
      price: 30,
      amount: "473ml",
      imageUrl: "/img/jumex-manzana-240x240.jpg",
      available: true,
    },
    {
      itemName: "Jugo Uva",
      price: 30,
      amount: "473ml",
      imageUrl: "/img/jumex-uva-240x240.jpg",
      available: true,
    },
    {
      itemName: "Jugo Mango",
      price: 30,
      amount: "473ml",
      imageUrl: "/img/jumex-mango-240x240.jpg",
      available: true,
    },
    {
      itemName: "Jugo Piña",
      price: 30,
      amount: "473ml",
      imageUrl: "/img/jumex-pina-240x240.jpg",
      available: true,
    },
    {
      itemName: "Jugo Durazno",
      price: 30,
      amount: "473ml",
      imageUrl: "/img/jumex-durazno-240x240.jpg",
      available: true,
    },
    {
      itemName: "Jugo Piña Coco",
      price: 30,
      amount: "473ml",
      imageUrl: "/img/jumex-pina-coco-240x240.jpg",
      available: true,
    },
  ],
  aguas: [
    {
      itemName: "Agua",
      price: 20,
      amount: "473ml",
      imageUrl: "/img/ciel-240x240.jpg",
      available: true,
    },
    {
      itemName: "Agua Mineral",
      price: 30,
      amount: "473ml",
      imageUrl: "/img/penafiel-240x240.webp",
      available: true,
    },
  ],
  botanas: [
    {
      itemName: "Chicharrones",
      price: 20,
      amount: "473ml",
      imageUrl: "/img/chicharron-240x240.png",
      available: true,
    },
  ],
};

export default menuData;
